1.product-introduction=产品简介
2.product-architecture=产品架构
2.deployment-guide=部署指南
3.console=管理控制台
3.user-center=个人中心
5.data-migration=数据迁移
3.create-a-data-migration-project=创建数据迁移项目
4.manage-data-migration-projects=管理数据迁移项目
6.data-source-management=数据源管理
1.add-a-data-source=添加数据源
7.o-m-and-monitoring=运维监控
2.server=机器
3.store=Store
4.jdbcwriter=JDBCWriter
5.checker=Checker
6.o-m-tickets=运维工单
7.description-of-component-parameters=组件参数说明
1.store-component-parameters=Store 组件参数说明
8.system-management=系统管理
2.alert-center=告警中心