1.product-introduction=Product Introduction
3.product-architecture=Architecture
5.user-guide=User Guide
1.console=OMS Community Edition console
3.user-center=User center
5.migration-solution=Create a data migration project
6.migration-project-management=Manage data migration projects
3.data-synchronization=Data synchronization
3.create-a-synchronization-channel=Create a data synchronization project
4.manage-a-data-synchronization-task=Manage data synchronization projects
4.manage-data-sources=Manage data sources
1.add-a-data-source=Add a data source
2.data-migration=Data migration
7.system-management=System management
2.alert-center-1=Alert center
6.o-m-manual=Operations and Maintenance Guide
3.machine=Server
4.component=Components
1.store-1=Store
2.connecter-1=Connector
3.jdbcwriter-1=JDBCWriter
4.checker-1=Checker
5.o-m-tickets=O&M tickets
6.description-of-component-parameters=Component parameters
1.store-component-parameters=Store parameters
2.connector-parameters=Connector parameters
7.alarm-reference=Alert Reference