3.product-introduction=Product Introduction
3.product-architecture=Architecture
5.user-guide=User Guide
1.management-console=OMS Community Edition console
3.user-center=User center
3.manage-data-sources=Manage data sources
1.add-a-data-source=Add a data source
5.data-migration-1=Data migration
5.migration-solution=Create a data migration project
6.migration-project-management=Manage data migration projects
6.data-synchronization-1=Data synchronization
3.create-a-synchronization-channel=Create a data synchronization project
4.manage-a-data-synchronization-task=Manage data synchronization projects
7.system-management=System management
2.alert-center-1=Alert center
6.o-m-manual=Operations and Maintenance Guide
3.machine=Server
4.component=Components
1.store=Store
2.connecter=Connector
3.jdbcwriter=JDBCWriter
4.checker=Checker
5.o-m-tickets=O&M tickets
6.description-of-component-parameters=Component parameters
1.store-component-parameters=Store parameters
2.connector-parameters=Connector parameters
7.alarm-reference-1=Alert Reference