1.product-introduction=产品简介
2.product-architecture=产品架构
2.deployment-guide=部署指南
3.user-guide=用户指南
3.console=管理控制台
3.user-center=个人中心
4.data-migration=数据迁移
3.create-a-data-migration-project=创建数据迁移项目
4.manage-data-migration-projects=管理数据迁移项目
5.data-synchronization=数据同步
3.create-a-synchronization-channel=创建数据同步项目
4.manage-a-data-synchronization-task=管理数据同步项目
6.data-source-management=数据源管理
1.add-a-data-source=添加数据源
8.system-management=系统管理
2.alert-center=告警中心
7.o-m-and-monitoring=运维指南
2.server=机器
3.components=组件
1.store=Store
2.connector=Connector
3.jdbcwriter=JDBCWriter
4.checker=Checker
4.o-m-tickets=运维工单
5.description-of-component-parameters=组件参数说明
1.store-component-parameters=Store 组件参数说明
2.connector-parameters=Connector 组件参数说明
8.alarm-reference=告警参考
9.api-reference=API 参考